#!/usr/bin/perl -w

# Copyright 2002 Paul A. Rombouts.

use strict;

print "/*
   This file was generated using $0.
   Do not edit this file, because your changes will be lost the next time $0 is run.
   Edit @ARGV instead.
*/
";

while(<>) {
    if(/^__BITVECTOR__$/) {
	my $prev=0;
	while(<>) {
	    chomp;
	    if($_ eq '') {last}
	    my $orig_text=$_;
	    my $bits=join '', map {($_ ne ' ')+0} (split //);
	    my $len= length($bits);
	    print '  ';
	    for(my $i=0; $i<$len; $i+=8) {
		print($prev?',':' ');
		printf("0x%02x",ord(pack("b8",substr($bits,$i,8))));
		$prev=1;
	    }
	    print "  /*$orig_text*/\n";
	}
    }
    else {print}    
}

