#!/usr/bin/perl -w
#
# A Perl script to convert tables represented by strings of characters
# into bit vector tables.
#
# Written by Paul A. Rombouts
#
# This file Copyright 2002 Paul A. Rombouts
# It may be distributed under the GNU Public License, version 2, or
# any higher version.  See section COPYING of the GNU Public license
# for conditions under which this file may be redistributed.
#

use strict;

print "/*
   This file was generated using $0.
   Do not edit this file, because your changes will be lost the next time $0 is run.
   Edit @ARGV instead.
*/
";

while(<>) {
    if(/^__BITVECTOR__$/) {
	my $prev=0;
	while(<>) {
	    chomp;
	    if($_ eq '') {last}
	    my $orig_text=$_;
	    my $bits=join '', map {($_ ne ' ')+0} (split //);
	    my $len= length($bits);
	    print '  ';
	    for(my $i=0; $i<$len; $i+=8) {
		print($prev?',':' ');
		printf("0x%02x",ord(pack("b8",substr($bits,$i,8))));
		$prev=1;
	    }
	    print "  /*$orig_text*/\n";
	}
    }
    else {print}    
}

