#!/bin/sh

#### THE SPOOL DIR IS "SPOOLDIR" IN THE LINE BELOW ####

wwwoffle_spool=SPOOLDIR

####

cd $wwwoffle_spool

# Set the path to include the search.cgi executable

PATH=$PATH:/usr/local/bin
PATH=$PATH:/usr/local/cgi-bin  # A possible location
PATH=$PATH:/usr/lib/cgi-bin    # The Debian location
export PATH

# Do the searching

UDMSEARCH_TEMPLATE=search/mnogosearch/conf/search.html
export UDMSEARCH_TEMPLATE

search.cgi 2> /dev/null
